# SPDX-FileCopyrightText: Maximilian Huber <oss@maximilian-huber.de>
#
# SPDX-License-Identifier: BSD-3-Clause

name:                packageurl
version:             0.2.0.0
github:              "maxhbr/packageurl"
license:             BSD3
author:              "Maximillian Huber"
maintainer:          "gh@maxhbr.de"
copyright:           "Maximilian Huber"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/maxhbr/packageurl#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- containers
- filepath
- network-uri
- split
- text
- uri-encode
- raw-strings-qq

library:
  source-dirs: src

tests:
  packageurl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - packageurl
    - hspec
    - QuickCheck

    - aeson
    - bytestring
    - containers
    - file-embed
